// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    user_id,
    body
) VALUES ($1, $2)
RETURNING message_id, user_id, body, created_at
`

type CreateMessageParams struct {
	UserID uuid.UUID
	Body   string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.UserID, arg.Body)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
