// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Body      string
	CreatedAt time.Time
}

type User struct {
	UserID    uuid.UUID
	Username  string
	CreatedAt time.Time
}
