// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username
) VALUES ($1)
RETURNING user_id, username, created_at
`

func (q *Queries) CreateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, username)
	var i User
	err := row.Scan(&i.UserID, &i.Username, &i.CreatedAt)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT user_id, username, created_at
FROM users
WHERE user_id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, userID)
	var i User
	err := row.Scan(&i.UserID, &i.Username, &i.CreatedAt)
	return i, err
}
